package com.elorserv.model;
// Generated 23 ene 2026, 13:27:32 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Ciclos generated by hbm2java
 */
@Entity
@Table(name = "ciclos")
public class Ciclos implements java.io.Serializable {

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String nombre;

    @JsonIgnore 
    @OneToMany(mappedBy = "ciclos")
    private Set<Modulos> modulos = new HashSet<>(0);

    @JsonIgnore 
    @OneToMany(mappedBy = "ciclos")
    private Set<Matriculaciones> matriculaciones = new HashSet<>(0);

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Set<Modulos> modulos, Set<Matriculaciones> matriculaciones) {
		this.nombre = nombre;
		this.modulos = modulos;
		this.matriculaciones = matriculaciones;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@JsonIgnore
	public Set<Modulos> getModulos() {
		return this.modulos;
	}

	public void setModulos(Set<Modulos> moduloses) {
		this.modulos = moduloses;
	}
	
	@JsonIgnore
	public Set<Matriculaciones> getMatriculaciones() {
		return this.matriculaciones;
	}

	public void setMatriculaciones(Set<Matriculaciones> matriculacioneses) {
		this.matriculaciones = matriculacioneses;
	}
	
}
