package com.elorserv.model;
// Generated 23 ene 2026, 13:27:32 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Modulos generated by hbm2java
 */
@Entity
@Table(name = "modulos")
public class Modulos implements java.io.Serializable {

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ciclo_id")
    private Ciclos ciclos;

    private String nombre;
    @Column(name = "nombre_eus")
    private String nombreEus;
    private int horas;
    private byte curso;

    @JsonIgnore 
    @OneToMany(mappedBy = "modulos")
    private Set<Horarios> horarios = new HashSet<>(0);

	public Modulos() {
	}

	public Modulos(Ciclos ciclos, String nombre, int horas, byte curso) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.horas = horas;
		this.curso = curso;
	}

	public Modulos(Ciclos ciclos, String nombre, String nombreEus, int horas, byte curso, Set<Horarios> horarios) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.nombreEus = nombreEus;
		this.horas = horas;
		this.curso = curso;
		this.horarios = horarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombreEus() {
		return this.nombreEus;
	}

	public void setNombreEus(String nombreEus) {
		this.nombreEus = nombreEus;
	}

	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	public byte getCurso() {
		return this.curso;
	}

	public void setCurso(byte curso) {
		this.curso = curso;
	}

	@JsonIgnore
	public Set<Horarios> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horarios> horarioses) {
		this.horarios = horarioses;
	}
}
