package com.elorserv.model;
// Generated 23 ene 2026, 13:27:32 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

/**
 * Tipos generated by hbm2java
 */
@Entity
@Table(name = "tipos")
public class Tipos implements java.io.Serializable {

	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    private String name;
    
    @Column(name = "name_eu")
    private String nameEu;

    @JsonIgnore 
    @OneToMany(mappedBy = "tipos") 
    private Set<Users> users = new HashSet<>(0);

	public Tipos() {
	}

	public Tipos(String name) {
		this.name = name;
	}

	public Tipos(String name, String nameEu, Set<Users> users) {
		this.name = name;
		this.nameEu = nameEu;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEu() {
		return this.nameEu;
	}

	public void setNameEu(String nameEu) {
		this.nameEu = nameEu;
	}
	
	@JsonIgnore
	public Set<Users> getUserses() {
		return this.users;
	}

	public void setUserses(Set<Users> userses) {
		this.users = userses;
	}
}
