package com.elorserv.model;
// Generated 23 ene 2026, 13:27:32 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {
	
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_id")
    private Tipos tipos;

    private String email;
    private String username;
    private String password;
    private String nombre;
    private String apellidos;
    private String dni;
    private String direccion;
    private String telefono1;
    private String telefono2;
    @Column(name = "argazkia_url")
    private String argazkiaUrl;
    @Column(name = "created_at")
    private Timestamp createdAt;
    @Column(name = "updated_at")
    private Timestamp updatedAt;

    // IMPORTANT: @JsonIgnore para evitar que el JSON del Login sea infinito
    @JsonIgnore 
    @OneToMany(mappedBy = "users")
    private Set<Matriculaciones> matriculaciones = new HashSet<>(0);

    @JsonIgnore 
    @OneToMany(mappedBy = "usersByAlumnoId")
    private Set<Reuniones> reunionesForAlumnoId = new HashSet<>(0);

    @JsonIgnore
    @OneToMany(mappedBy = "users")
    //@JsonManagedReference(value = "users-horarios")
    private Set<Horarios> horarios = new HashSet<>(0);

    @JsonIgnore 
    @OneToMany(mappedBy = "usersByProfesorId")
    private Set<Reuniones> reunionesForProfesorId = new HashSet<>(0);
	
	public Users() {
	}

	public Users(Tipos tipos, String email, String username, String password) {
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
	}

	public Users(Tipos tipos, String email, String username, String password, String nombre, String apellidos,
			String dni, String direccion, String telefono1, String telefono2, String argazkiaUrl, Timestamp createdAt,
			Timestamp updatedAt, Set<Matriculaciones> matriculaciones, Set<Reuniones> reunionesForAlumnoId, Set<Horarios> horarios,
			Set<Reuniones> reunionesForProfesorId) {
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.argazkiaUrl = argazkiaUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.matriculaciones = matriculaciones;
		this.reunionesForAlumnoId = reunionesForAlumnoId;
		this.horarios = horarios;
		this.reunionesForProfesorId = reunionesForProfesorId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tipos getTipos() {
		return this.tipos;
	}

	public void setTipos(Tipos tipos) {
		this.tipos = tipos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getArgazkiaUrl() {
		return this.argazkiaUrl;
	}

	public void setArgazkiaUrl(String argazkiaUrl) {
		this.argazkiaUrl = argazkiaUrl;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	public Set<Matriculaciones> getMatriculaciones() {
		return this.matriculaciones;
	}

	public void setMatriculaciones(Set<Matriculaciones> matriculacioneses) {
		this.matriculaciones = matriculacioneses;
	}

	public Set<Reuniones> getReunionesForAlumnoId() {
		return this.reunionesForAlumnoId;
	}

	public void setReunionesForAlumnoId(Set<Reuniones> reunionesForAlumnoId) {
		this.reunionesForAlumnoId = reunionesForAlumnoId;
	}
	
	@JsonIgnore
	public Set<Horarios> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horarios> horarioses) {
		this.horarios = horarioses;
	}

	public Set<Reuniones> getReunionesForProfesorId() {
		return this.reunionesForProfesorId;
	}

	public void setReunionesForProfesorId(Set<Reuniones> reunionesForProfesorId) {
		this.reunionesForProfesorId = reunionesForProfesorId;
	}
}
