package com.elorserv.model;
// Generated 21 ene 2026, 14:13:06 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set moduloses = new HashSet(0);
	private Set matriculacioneses = new HashSet(0);

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Set moduloses, Set matriculacioneses) {
		this.nombre = nombre;
		this.moduloses = moduloses;
		this.matriculacioneses = matriculacioneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set moduloses) {
		this.moduloses = moduloses;
	}

	public Set getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

}
