package com.elorserv.model;
// Generated 21 ene 2026, 14:13:06 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Matriculaciones generated by hbm2java
 */
public class Matriculaciones implements java.io.Serializable {

	private Integer id;
	private Ciclos ciclos;
	private Users users;
	private byte curso;
	private Date fecha;

	public Matriculaciones() {
	}

	public Matriculaciones(Ciclos ciclos, Users users, byte curso, Date fecha) {
		this.ciclos = ciclos;
		this.users = users;
		this.curso = curso;
		this.fecha = fecha;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public byte getCurso() {
		return this.curso;
	}

	public void setCurso(byte curso) {
		this.curso = curso;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
